### ISSUE TITLE
Неверный порядок плагинов

### ISSUE THREAD

**Issue by Ser-Gen** [verstak-int/intcss#2]
Не смотря [на предупреждение](https://github.com/travco/postcss-extend#installation) [`postcss-extend`](https://github.com/travco/postcss-extend) должен идти после [`postcss-nested`](https://github.com/postcss/postcss-nested).

```scss
%commonPadding {
    padding-left: 15px;
}
.container {
    .extendingClass {
        @extend %commonPadding;
    }
}
```

Ожидаем увидеть

```css
.container .extendingClass {
    padding-left: 15px;
}
```

Получается

```css
.extendingClass {
    padding-left: 15px;
}
.container {
}
```
